
package(default_visibility = ["//visibility:public"])

py_library(
    name = "tfg_custom_ops_py",
    srcs = ['__init__.py'],
    deps = [
        "//tfg_custom_ops/basis_proj:basis_proj_py",
        "//tfg_custom_ops/build_grid_ds:build_grid_ds_py",
        "//tfg_custom_ops/compute_keys:compute_keys_py",
        "//tfg_custom_ops/compute_pdf:compute_pdf_py",
        "//tfg_custom_ops/find_neighbors:find_neighbors_py",
        "//tfg_custom_ops/sampling:sampling_py",
    ],
    srcs_version = "PY2AND3",
)