inherit_from: configs/unconditional/onet_sofas.yaml
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_uncond_sofas-bf6c039d.pt
generation:
  generation_dir: pretrained
