inherit_from: configs/unconditional/onet_cars.yaml
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_uncond_cars-59320701.pt
generation:
  generation_dir: pretrained
