inherit_from: configs/voxels/onet.yaml
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_voxel2mesh-52ee34d4.pt
generation:
  generation_dir: pretrained
