inherit_from: configs/img/onet.yaml
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_img2mesh_3-f786b04a.pt
generation:
  generation_dir: pretrained
